"use client";

import { 
  Settings, 
  User, 
  MapPin, 
  Phone, 
  Globe, 
  Hash, 
  FileText, 
  Printer, 
  Save, 
  Palette,
  Bell
} from "lucide-react";
import { PRESS_CONFIG } from "@/lib/config";
import { useState } from "react";

import { useLanguage } from "@/lib/context/LanguageContext";

export default function SettingsPage() {
  const { t } = useLanguage();
  const [activeTab, setActiveTab] = useState("business");

  const tabs = [
    { id: "business", label: t("Business Details", "బిజినెస్ వివరాలు"), icon: Settings },
    { id: "profile", label: t("My Profile", "నా ప్రొఫైల్"), icon: User },
    { id: "print", label: t("Printing Config", "ప్రింటింగ్ కాన్ఫిగ్"), icon: Printer },
  ];

  return (
    <div className="space-y-8">
      <div className="flex flex-col lg:flex-row gap-8">
         {/* Sidebar Tabs */}
         <div className="w-full lg:w-64 space-y-2">
            {tabs.map((tab) => (
               <button 
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all  ${
                    activeTab === tab.id 
                      ? "bg-primary text-white shadow-lg shadow-primary/20" 
                      : "bg-white text-gray-600 hover:bg-gray-50 border border-gray-100"
                  }`}
               >
                  <tab.icon className="w-5 h-5" />
                  <div className="text-left">
                     <p className="text-sm">{tab.label}</p>
                  </div>
               </button>
            ))}
         </div>

         {/* Settings Content Area */}
         <div className="flex-1 bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
            {activeTab === "business" && (
              <div className="p-8 space-y-8">
                <div className="flex items-center justify-between border-b border-gray-100 pb-6">
                  <h2 className="text-xl  text-gray-900">{t("Business Details", "బిజినెస్ వివరాలు")}</h2>
                  <button className="bg-primary text-white px-4 py-2 rounded-lg flex items-center gap-2  hover:opacity-90 transition-all">
                     <Save className="w-4 h-4" /> {t("Save Changes", "మారపులను సేవ్ చేయండి")}
                  </button>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                   <div className="space-y-2">
                      <label className="text-xs  text-gray-500 uppercase flex items-center gap-1"><Printer className="w-3 h-3" /> {t("Business Name", "వ్యాపారం పేరు")}</label>
                      <input type="text" value={PRESS_CONFIG.name} className="w-full p-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all" />
                   </div>
                   <div className="space-y-2">
                      <label className="text-xs  text-gray-500 uppercase flex items-center gap-1"><MapPin className="w-3 h-3" /> {t("Address", "చిరునామా")}</label>
                      <input type="text" value={PRESS_CONFIG.address} className="w-full p-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all" />
                   </div>
                   <div className="space-y-2">
                      <label className="text-xs  text-gray-500 uppercase flex items-center gap-1"><Phone className="w-3 h-3" /> {t("Contact Phone", "ఫోన్ నంబర్")}</label>
                      <input type="text" value={PRESS_CONFIG.phone} className="w-full p-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all" />
                   </div>
                   <div className="space-y-2">
                      <label className="text-xs  text-gray-500 uppercase flex items-center gap-1"><Hash className="w-3 h-3" /> {t("GST Number", "GST నంబర్")}</label>
                      <input type="text" value={PRESS_CONFIG.gstNumber || "Not Provided"} className="w-full p-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all" />
                   </div>
                </div>

                <div className="bg-gray-50 p-6 rounded-2xl border border-dashed border-gray-200">
                    <h3 className="text-sm  text-gray-900 mb-2">{t("Advance Options", "అడ్వాన్స్డ్ ఎంపికలు")}</h3>
                    <p className="text-xs text-gray-500 leading-relaxed mb-4">{t("Warning: Any changes made to these business details will be reflected on all new invoices and estimates generated by the system.", "హెచ్చరిక: ఈ వ్యాపార వివరాలలో చేసే ఏవైనా మార్పులు సిస్టమ్ ద్వారా రూపొందించబడిన అన్ని కొత్త ఇన్వాయిస్ మరియు ఎస్టిమేట్స్ పై కనిపిస్తాయి.")}</p>
                </div>
              </div>
            )}

            {activeTab !== "business" && (
               <div className="flex flex-col items-center justify-center p-20 text-center space-y-4">
                  <div className="bg-gray-50 p-6 rounded-full">
                     <Settings className="w-12 h-12 text-gray-300 animate-spin-slow" />
                  </div>
                  <h2 className="text-lg  text-gray-900">{t("Module Under Development", "ఈ విభాగం ఇంకా తయారవుతోంది")}</h2>
                  <p className="text-sm text-gray-500 max-w-xs">{t("We are currently building this settings module. It will be available in the next version update.", "మేము ప్రస్తుతం ఈ సెట్టింగులను తయారు చేస్తున్నాము. ఇది తదుపరి వెర్షన్ లో అందుబాటులో ఉంటుంది.")}</p>
               </div>
            )}
         </div>
      </div>
    </div>
  );
}
